### PR TITLE
make flushPromises a test-util

### LINKED ISSUE #364: Investigate connection errors thrown on client tests
Reproduce run `yarn test` on client. Tests Pass however the following is thrown :

```
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/app/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at Request.client.on.err (/app/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
          at Request.emit (events.js:203:15)
          at Request.onRequestError (/app/node_modules/request/request.js:881:8)
          at ClientRequest.emit (events.js:198:13)
          at Socket.socketErrorListener (_http_client.js:392:9)
          at Socket.emit (events.js:198:13)
          at emitErrorNT (internal/streams/destroy.js:91:8)
          at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
          at process._tickCallback (internal/process/next_tick.js:63:19) undefined
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/app/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at Request.client.on.err (/app/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
          at Request.emit (events.js:203:15)
          at Request.onRequestError (/app/node_modules/request/request.js:881:8)
          at ClientRequest.emit (events.js:198:13)
          at Socket.socketErrorListener (_http_client.js:392:9)
          at Socket.emit (events.js:198:13)
          at emitErrorNT (internal/streams/destroy.js:91:8)
          at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
          at process._tickCallback (internal/process/next_tick.js:63:19) undefined
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/app/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at Request.client.on.err (/app/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
          at Request.emit (events.js:203:15)
          at Request.onRequestError (/app/node_modules/request/request.js:881:8)
          at ClientRequest.emit (events.js:198:13)
          at Socket.socketErrorListener (_http_client.js:392:9)
          at Socket.emit (events.js:198:13)
          at emitErrorNT (internal/streams/destroy.js:91:8)
          at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
          at process._tickCallback (internal/process/next_tick.js:63:19) undefined
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
[31m      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/app/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at Request.client.on.err (/app/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
          at Request.emit (events.js:203:15)
          at Request.onRequestError (/app/node_modules/request/request.js:881:8)
          at ClientRequest.emit (events.js:198:13)
          at Socket.socketErrorListener (_http_client.js:392:9)
          at Socket.emit (events.js:198:13)
          at emitErrorNT (internal/streams/destroy.js:91:8)
          at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
          at process._tickCallback (internal/process/next_tick.js:63:19) undefined
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/app/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at Request.client.on.err (/app/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
          at Request.emit (events.js:203:15)
          at Request.onRequestError (/app/node_modules/request/request.js:881:8)
          at ClientRequest.emit (events.js:198:13)
          at Socket.socketErrorListener (_http_client.js:392:9)
          at Socket.emit (events.js:198:13)
          at emitErrorNT (internal/streams/destroy.js:91:8)
          at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
          at process._tickCallback (internal/process/next_tick.js:63:19) undefined
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/app/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at Request.client.on.err (/app/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
          at Request.emit (events.js:203:15)
          at Request.onRequestError (/app/node_modules/request/request.js:881:8)
          at ClientRequest.emit (events.js:198:13)
          at Socket.socketErrorListener (_http_client.js:392:9)
          at Socket.emit (events.js:198:13)
          at emitErrorNT (internal/streams/destroy.js:91:8)
          at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
          at process._tickCallback (internal/process/next_tick.js:63:19) undefined
```

Reproducible locally and in ci.

### PR DESCRIPTION
**Pull request by Cooryd**
closes #364 

Makes `flushPromise` a generic function for use throughout the tests. Fixes errors thrown by replacing the use of `setImmediate` to `setTimeout`.

Removes unused Icon dependency from component.

__we did attempt to use the `flush-promises` library, however this uses `setImmediate` in the context of our tests so still causes the error to be thrown__

### CODE REVIEW

File: client/test-utils/flushPromises.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+function flushPromises() {
```
Comment (Cooryd) [inline client/test-utils/flushPromises.ts]: This is almost identical code to https://github.com/kentor/flush-promises/blob/master/index.js so wondering as this'll be a dev dependency whether we just use the npm `flush-promises` package instead, thoughts?

Comment (erezmus) [reply client/test-utils/flushPromises.ts]: we are using flush-promises in the event-bus for tests so maybe a reason for standardisation albeit quite weak if we are moving to many repos.

Comment (Cooryd) [reply client/test-utils/flushPromises.ts]: I'm for moving to use the published package then. Can't see many benefits of having to maintain the dozen lines of code ourself. Also we're not covering test-utils with unit tests where as the package does have coverage.

Comment (Cooryd) [reply client/test-utils/flushPromises.ts]: scrap that, this is evaluating to setInterval which was causing the console errors. Lets stick with the local code instead.
 https://github.com/kentor/flush-promises/blob/46f58770b14fb74ce1ff27da00837c7e722b9d06/index.js#L1

Comment (diversemix) [reply client/test-utils/flushPromises.ts]: Also check here: https://medium.com/better-programming/process-nexttick-vs-setimmediate-vs-settimeout-explained-wrt-different-event-loop-phases-c0506b12921d
